channels:
  - conda-forge
dependencies:
  - jupyter-server-proxy>=1.4
  - pip
  - websockify
  - numpy
  - pandas
  - scipy
  - scikit-image
  - scikit-learn
  - requests
  - pip:
    - jupyter-desktop-server
    - napari[all]
    - trackpy